# Generated by Django 3.2.13 on 2022-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='nomc',
        ),
    ]
