# Generated by Django 3.2.13 on 2022-05-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_avion_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avion',
            old_name='type',
            new_name='constructeur',
        ),
    ]
